[env]
TERM = "xterm-256color"

[window]
decorations = "full"
opacity = 1
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[font]
size = 13.0

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
background            = "#1E1E1E"
foreground            = "#CCCCCC"
